\newpage{}

# Executive summary

\TeX{} has many desirable features, such as math equation formatting and typesetting, which are currently not available in R. The `dvir` package extends R to draw \TeX{} output on R graphics. By extending the usability and functionality of the `dvir` package it better streamlines the workflow of making R graphics with some \TeX{} output - rather than making some graphics in R and exporting to \LaTeX{} itself or an image editor like Photoshop to add \TeX{} or \TeX{}-like output, this can all be done in R through a simple interface from the `dvir` package. Three improvements to the `dvir` package are investigated and discussed in this report.

Running functions from the `dvir` package took a long time which. The speed of the package was increased by making two changes - removing redundant code that meant the `dvir` package was searching for fonts three times instead once, and allowing font information to be cached so once font information was found the `dvir` package did not need to search again for that font. 

The latest version of R adds functionality of linear and radial gradient fills. This means gradient fill information from \Tikz{} graphics, a \TeX{} package, could be generated by `dvir` and manipulated to be fed into R. This was not implemented as the complexity of the gradient definition from \Tikz{} resulted in "warped" gradient fills which are not possible in R. 

The `dvir` package currently performs any alignment based on the bounding box of the text but aligning with the baseline of the text is more desirable. \TeX{} output does not explicitly state a baseline value for a piece of text so some algorithms for determining the text baselines were implemented in an R function to test their usefulness. One of these algorithms performs particular well for all tested examples, including multi-line text.

The magnitude of the speed increase alone makes `dvir` much more practical as it allows much faster testing of code and allows for more complicated graphics with many calls to the `dvir` package. The ability to align text to its baseline means graphics with the addition of \TeX{}, for example in lattice plot headers, can be aligned with one another and not require "touching up" outside of R.

This report, source code and associated files can be found on GitHub:  https://github.com/ajvandervoorn/honours_dissertation