\newpage{}

# Introduction

R has the ability to display mathematical symbols and equations in graphics using the "plotmath" feature, interpreting everything within a call to `expression()` as a mathematical equation.

<!--- Need to think of a better example than this one, ideally one that brings in our x - mu somehow --->

```{r expressionPlot, fig.cap="A plot with axis labels made using `expression()`."}
mu <- 1:5
opar <- par(mar = par()$mar + c(0, 1, 0, 0))
plot(mu, mu ^ 2 / 2, xlab = expression(mu), ylab = "", yaxt = "n")
axis(2, las = 1)
mtext(expression(frac(mu ^ 2, 2)), side = 2, line = 3, las = 1)
```

This provides us with most of the symbols used for equations, such as brackets and fractions, and formats them in a layout resembling \TeX{}, but it is limited in its fonts. Compare the y-axis label above with how it looks when created by \LaTeX{} in figure \ref{muOver2}.

\begin{figure}\label{muOver2}
\begin{equation*}
\dfrac{\mu^2}{2}
\end{equation*}
\caption{The \(y\)-axis label from above, when created in \LaTeX}
\end{figure}

<!---
Use this code for above example, just need to find a way to caption and reference it. Also delete image from figures folder when done



could use \[\dfrac{\mu^2}{2}\] if that was easier too?
--->

The difference is stark and there are several approaches in R which can get us closer to the \LaTeX{} result (Murrell, 2018 [Revisiting Mathematical Equations in R: The 'dvir' package]).

<!--- 
for these examples following, say that Paul's report descirbes the limitations of these approaches, and replicate the examples
--->
  - [**Example:** use `extrafont` and `fontcm` packages, embed CM fonts in PDF]

  - [**Example:** use `tikzDevice` package, which creates PGF/TikZ version of plot (and as such converts all text in plot to LaTeX (including labels))]

What we want is a middle ground - being able to harness the power of \TeX{} and its typsetting capabilities on our choice of text or equation in R graphics. This is where the `dvir` package comes in - providing a simple user interface, in the style of the R `grid` graphics package [Reference R grid graphics here], by way of the `grid.latex()` function:

  - [**Example:** example of grid-based plot, changing labels and/or title with `grid.latex()`. Maybe ggplot2?]

## Where this project fits in

The `dvir` package already worked really well in a lot of cases. There were however plenty more desirable features of \TeX{} and its extensions though that had not yet been implemented by `dvir`. The power of this package is from ensuring it is comprehensive enough to meet a user's entire \TeX{} needs in R graphics without having to leave R to do annotations in \LaTeX{} itself (or Photoshop/Illustrator!). 

By keeping things "in R" users only need to learn R (and basic \TeX) code to create their graphics and their work is in one place and easily reproducible. It may not be realistic to *completely* replicate \TeX{} in R, however there were several aspects of the package identified as having a lot of potential to greatly increase its usefulness. The aspects identified were:

* the speed of the package - anecdotally it took a while to generate graphics, especially if there were many `grid.latex()` calls
* expand `dvir`'s capability of creating TikZ drawings by adding support for linear gradient fills
* adding the ability to align text from `grid.latex()` to a baseline - the natural line on which characters sit