\newpage{}

# Background

## \TeX{}

\TeX{} is a program to format and typeset text, and includes some basic macros to do this. \LaTeX{} is a higher-level implementation of \TeX{}, basically consisting of a lot more macros, creating a much more user-friendly interface to \TeX{}. For example, \LaTeX{} allows one to create a document with numbered sections, title pages and bibliographies without having to write complicated \TeX{} macros themself. There are other extensions to \TeX{} that do similar things to \LaTeX{} too.

## DVI

A \TeX{} or \LaTeX{} file is just plain text, so there needs to be a step to translate this plain text to what you will see on a formatted document on a screen or page. A DVI (DeVice Independent) file is a binary file *describing* the layout of the document. For example, the height of the page, what characters to display and where, and the fonts to be used.

<!---
Explain DVI more here (and less in next section explaining dvir packages)

A DVI file describes the visual layout of the document to produce but is not specific to any type of output file (PDF, HTML, etc.)

--->

## The (pre-existing) `dvir` package {#dvirDesc}

<!---
(not sure how to make clear this is all stuff that was in 'dvir' before any of my work (and the fact I didn't change any of this high level stuff))  

DVIR BACKGROUND INFO (CHECK IF IT IS COVERED BELOW):
  Font sweep (check if this bit is added):
    run through the DVI file, identify all the fonts used, and find and record the font file locations on the system.

  The purpose of `definePDFFont()` is to do a sweep of the DVI file from `grid.latex()` looking for all fonts required, before recording the font names in the font config file, searching the relevant directories for the font files and encoding the fonts. A variable `fonts` is saved with all this information. The further sweeps over the DVI file to determine the bounding box of each character and thus entire image, and to create grid grobs and viewports each redundantly called `definePDFFont()` rather than referring to the already existing variable `fonts` from the first sweep.
--->

In a simplified form, `dvir` works by providing a high level function, `grid.latex()`, to call with the \TeX{} code of the expression or text to be displayed.

<!---
This isn't the label from earlier! Either don't relate this to the label or redo the caption or redo the text
--->
```{r, fig.width = 0.4, fig.height = 0.4, fig.cap = "Using the `dvir` function `grid.latex()`"}
library(dvir)
grid.latex("$x - \\mu$")
```

The following steps are taken when `grid.latex()` runs:

\begin{enumerate}
  \item A \TeX{} document is created with the expression and a changeable default preamble and postamble.

  - [**Example:** TeX document with pre- and post-amble]
  
  \item This TeX document is then processed using the local \TeX{} installation to create a DVI (DeVice Independent) file.
  
  \item The DVI file is read into R. As DVI files are binary they are not easily readable by humans but the `dvir` function `readDVI()` translates the DVI file into readable text.

  - [**Example:** Extract of DVI file using `readDVI()` (not the whole thing, just the bit relevant to our example ($x - \mu$))]
  
  \item Three "sweeps" of the DVI file are completed to extract necessary information about what to display in R (and where and how to display it):
  \begin{itemize}
    \item Font sweep: Gather the names of all fonts used in the DVI file and locate the relevant font files on the local machine. The font information is stored in a R list as well as a `fontconfig` file.
    \item Metric sweep: To determine the overall bounding box (size) of the expression to display. This bounding box is used to create a `grid` viewport which can encompass the entire \TeX{} passed to `grid.latex()` expression using the native DVI coordinates.
    \item Grid sweep: Convert all text and symbols into *grobs* (grid graphical objects) 
  \end{itemize}
  \item These grobs are then displayed in the R graphics device as per the `grid` package.
\end{enumerate}